"""empty message

Revision ID: 58342e980d73
Revises: 93ed8eea8d7b
Create Date: 2024-11-20 10:26:06.416558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58342e980d73'
down_revision = '93ed8eea8d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fans')
    # ### end Alembic commands ###
