"""empty message

Revision ID: 93ed8eea8d7b
Revises: ec9e16f6b5ba
Create Date: 2024-11-19 13:29:11.632695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93ed8eea8d7b'
down_revision = 'ec9e16f6b5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_subscription', sa.Date(), nullable=False))
        batch_op.drop_column('date_of_suscription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_suscription', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_of_subscription')

    # ### end Alembic commands ###
