"""empty message

Revision ID: a04aeaa7a19d
Revises: 58342e980d73
Create Date: 2024-11-20 10:29:06.469730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04aeaa7a19d'
down_revision = '58342e980d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_subscription', sa.Date(), nullable=False))

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fan_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fans', ['fan_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('fan_id')

    with op.batch_alter_table('fans', schema=None) as batch_op:
        batch_op.drop_column('date_of_subscription')

    # ### end Alembic commands ###
